name: NPM Test Actions

on:
    workflow_dispatch:

jobs:
  recons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Amass Enum
        uses: fguisso/amass-action@npm
        with:
          brute: true
          domains: target.com
          output: hosts.txt

      - name: 💥 Naabu - Port Scanner
        uses: projectdiscovery/naabu-action@main
        with:
          list: hosts.txt
          output: urls.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: final-recon
          path: |
            hosts.txt
            urls.txt
