name: Testing

on:
    workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: |
            echo "test=hello" >> $GITHUB_ENV
            echo ${{ env.test }}
        shell: bash
      
      - run: |
            echo "test=world" >> $GITHUB_ENV
            echo ${{ env.test }}
        shell: bash
      
      - run: |
            echo "Final test \n"
            echo ${{ env.test }}
        shell: bash
      
